project:
  type: website

website:
  title: "."
  navbar:
    left:
      - href: index.md
        text: Home
      - about.md

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    highlight-style: github

filters:
- obsidian-callouts.lua


